[license] Add header to test java files
apache/incubator-paimon pull request #1190
Opened 2023-05-22 03:11 UTC by JingsongLi

### Purpose

Even java files in resources, we need to add header to these files.

2023-05-22 07:30 UTC, carp84 requested changes
It seems to me that in our [apache-rat plugin configuration](https://github.com/apache/incubator-paimon/blob/master/pom.xml#L411) (in the pom file) we have excluded all codesplit resources, where we are missing license headers and trying to fix in this PR. I suggest we carefully review our apache-rat configuration and do necessary change to make sure no more unexpected exclusions.

Note: files such as `paimon-common/src/test/resources/codesplit/groups` should be excluded indeed, and we need to carefully check and make sure that `mvn verify` has the precise coverage (no more no less).

2023-05-24 11:52 UTC, carp84 commented on pom.xml
The current changes LGTM, and I have confirmed `mvn verify` could pass.

Could you further make sure whether the below exclusions in the rat check configuration are as expected and already with necessary notice/license declaration?:
1. docs/assets/github.css (L399)
2. docs/static/js/anchor.min.js (L400)
3. docs/layouts/shortcodes/generated/** (L401)

And please make sure the exclusion of font-awesome (L395) is removed in PR#1192 if the dependency is removed there. Thanks.

2023-05-24 14:08 UTC, JingsongLi commented on pom.xml
>1. docs/assets/github.css (L399)

Add license in https://github.com/apache/incubator-paimon/pull/1192

>2.docs/static/js/anchor.min.js (L400)

Already noticed in NOTICE and LICENSE

>3.docs/layouts/shortcodes/generated/** (L401)

Addressed, I generated in `paimon-doc`.

Very thanks Yu.

2023-05-25 07:50 UTC, carp84 approved these changes
The latest changes LGTM, and I've confirmed `mvn verify` could pass locally. Thanks for the efforts @JingsongLi

2023-05-25 07:52 UTC, merged