[docs] spark rename paimon table
apache/incubator-paimon pull request #1639
Opened 2023-07-24 09:42 UTC by leaves12138

We can't put catalog name before the renamed-to table, it will throw an error

2023-07-24 11:14 UTC, JingsongLi requested changes
You can add this in `/how-to/altering-tables`.

2023-07-27 05:51 UTC, JingsongLi commented on docs/content/engines/spark3.md
> +{{< /hint >}}
revert this?

2023-07-27 05:54 UTC, leaves12138 commented on docs/content/engines/spark3.md
> +{{< /hint >}}
done

2023-07-28 07:53 UTC, JingsongLi commented on docs/content/how-to/altering-tables.md
> +{{< hint info >}}
remove `hint info`, such a long hint is not good

2023-07-31 06:05 UTC, JingsongLi approved these changes
+1

2023-07-31 06:06 UTC, merged