[improve]  Unaware-bucket table do compaction async, uncoupled with CheckpointBarrier.
apache/incubator-paimon pull request #1690
Opened 2023-07-31 08:21 UTC by leaves12138

Unaware-bucket table do compaction async, uncoupled with CheckpointBarrier.

Cause compaction may stock the checkpoint acknowledgement, but we actually don't need wait for all the compaction tasks finished to complete the checkpoint.

Use the ExecutorService with max 100 tasks queue running background to execute compaction tasks.

Worker Task    <---------    ResultQueue
     |                                                      /\
     |                  (   o     o    )                  |
     |                          -                           |
     |                                                       |
     |                                                       |
    \/                                                       |
Task Queue  ---------------> ExecutorService

2023-07-31 08:35 UTC, JingsongLi requested changes
Add tests for `AppendOnlyTableCompactionWorkerOperator`.

2023-07-31 08:36 UTC, JingsongLi commented on paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperator.java
> +                new ThreadPoolExecutor(
See `AbstractFileStoreWrite`, how to new an executor and close executor.

2023-07-31 08:38 UTC, JingsongLi commented on paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperator.java
Uncommit files should be deleted in close.

2023-07-31 08:39 UTC, JingsongLi commented on paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperator.java
>      private transient List<CommitMessage> result;
You can just change this to `LinkedBlockingQueue` and avoid lock.

2023-08-01 01:15 UTC, JingsongLi commented on paimon-flink/paimon-flink-common/src/test/java/org/apache/paimon/flink/FileStoreTableTestBase.java
> +public abstract class FileStoreTableTestBase {
Use `TableTestBase`?

2023-08-01 08:10 UTC, JingsongLi commented on paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperator.java
> +                if (!future.isDone()) {
```
if (!future.isDone() && !waitCompaction) {
    break;
}
....
```

2023-08-01 08:10 UTC, JingsongLi commented on paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperator.java
> +                    List<DataFileMeta> fileMetas =
See `TableCommit.abort`?

2023-08-01 08:16 UTC, leaves12138 commented on paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/AppendOnlyTableCompactionWorkerOperator.java
> +                if (!future.isDone()) {
reasonable

2023-08-02 03:29 UTC, JingsongLi approved these changes
+1

2023-08-02 03:29 UTC, merged